# Generated by Django 5.1.4 on 2026-05-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_batiment', models.CharField(max_length=30, unique=True)),
                ('nombre_logements', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='immo.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to='immo.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_appartement', models.CharField(max_length=50)),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='immo.agence')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='immo.batiment')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='immo.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('attente', 'En attente'), ('retard', 'En retard')], default='attente', max_length=20)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='immo.agence')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='immo.location')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_client', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('resident', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires_immobiliers', to='immo.agence')),
            ],
        ),
        migrations.AddField(
            model_name='batiment',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='immo.proprietaire'),
        ),
    ]
