# Generated by Django 5.1.4 on 2026-06-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0002_employe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to='immo.employe'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='paiements/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('carte', 'Carte bancaire')], default='espece', max_length=30),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mois',
            field=models.CharField(default=1, help_text='Exemple : Juin 2026', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_recu',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='signature_employe',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='signature_locataire',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
