# Generated by Django 5.1.4 on 2026-06-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0003_alter_paiement_options_paiement_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='acte_naissance',
            field=models.FileField(blank=True, null=True, upload_to='locataires/actes_naissance/'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='adresse_actuelle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_expiration_piece',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='employeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='pays',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locataires/photos/'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='locataires/pieces_identite/'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='revenu_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='ville',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]