# Generated by Django 6.0.5 on 2026-06-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0004_locataire_acte_naissance_locataire_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='caution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='location',
            name='caution_payee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='date_caution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='observation_caution',
            field=models.TextField(blank=True, null=True),
        ),
    ]