# Generated by Django 6.0.5 on 2026-06-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0005_location_caution_location_caution_payee_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="locataire",
            name="caution",
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AddField(
            model_name="locataire",
            name="caution_payee",
            field=models.BooleanField(
                default=False,
            ),
        ),

        migrations.AddField(
            model_name="locataire",
            name="date_caution",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="locataire",
            name="observation_caution",
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="locataire",
            name="date_debut",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

    ]