# Generated by Django 6.0.5 on 2026-06-29 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0006_locataire_active_locataire_caution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ChambreLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='immo.batiment')),
            ],
            options={
                'unique_together': {('batiment', 'numero')},
            },
        ),
    ]