# Generated by Django 6.0.5 on 2026-06-29 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0007_alter_locataire_date_creation_chambrelogement'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='immo.chambrelogement'),
        ),
    ]
