# Generated by Django 6.0.5 on 2026-07-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0009_paiement_commission_agence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMensuelProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=30)),
                ('total_loyers', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('part_agence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('part_proprietaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_mensuels', to='immo.agence')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_mensuels', to='immo.proprietaire')),
            ],
        ),
    ]
