# Generated by Django 6.0.5 on 2026-07-08 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0011_construction_etatconstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type_operation', models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat')], default='vente', max_length=20)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('construction', 'En construction'), ('vendu', 'Vendu'), ('reserve', 'Réservé')], default='libre', max_length=30)),
                ('qualite', models.CharField(choices=[('20/20', '20/20 - Excellent'), ('18/20', '18/20 - Très bon'), ('15/20', '15/20 - Bon'), ('12/20', '12/20 - Moyen'), ('10/20', '10/20 - À vérifier')], default='15/20', max_length=20)),
                ('pays', models.CharField(default='Mali', max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie', models.DecimalField(decimal_places=2, default=0, help_text='Superficie en m²', max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_disponible', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrains', to='immo.agence')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrains', to='immo.proprietaire')),
            ],
        ),
    ]
