# Generated by Django 6.0.5 on 2026-07-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0012_terrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(choices=[('agence', 'Dépense de l’agence'), ('proprietaire', 'Dépense du propriétaire')], max_length=20)),
                ('categorie', models.CharField(choices=[('entretien', 'Entretien'), ('reparation', 'Réparation'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('gardiennage', 'Gardiennage'), ('nettoyage', 'Nettoyage'), ('taxe', 'Taxe'), ('assurance', 'Assurance'), ('transport', 'Transport'), ('administration', 'Administration'), ('construction', 'Construction'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/')),
                ('ajoute_par', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='immo.agence')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='immo.proprietaire')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-date_creation'],
            },
        ),
    ]
