# Generated by Django 6.0.5 on 2026-07-10 02:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0013_depense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportmensuelproprietaire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Rapport mensuel propriétaire', 'verbose_name_plural': 'Rapports mensuels propriétaires'},
        ),
        migrations.AddField(
            model_name='rapportmensuelproprietaire',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rapportmensuelproprietaire',
            name='depenses_agence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rapportmensuelproprietaire',
            name='depenses_proprietaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rapportmensuelproprietaire',
            name='net_agence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rapportmensuelproprietaire',
            name='net_proprietaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
