# Generated by Django 6.0.5 on 2026-07-16 08:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0014_alter_rapportmensuelproprietaire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=180)),
                ('type_centre', models.CharField(choices=[('centre_commercial', 'Centre commercial'), ('galerie', 'Galerie commerciale'), ('marche', 'Marché'), ('gare', 'Gare'), ('station', 'Station'), ('zone_activite', 'Zone d’activité'), ('immeuble_commercial', 'Immeuble commercial'), ('autre', 'Autre')], default='centre_commercial', max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=120)),
                ('quartier', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres_commerciaux', to='immo.agence')),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_commerciaux', to='immo.batiment')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_commerciaux', to='immo.proprietaire')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LocalCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('type_local', models.CharField(choices=[('boutique', 'Boutique'), ('restaurant', 'Restaurant'), ('bureau', 'Bureau'), ('atelier', 'Atelier'), ('entrepot', 'Entrepôt'), ('kiosque', 'Kiosque'), ('station', 'Station'), ('salon', 'Salon'), ('pharmacie', 'Pharmacie'), ('supermarche', 'Supermarché'), ('lieu_travail', 'Lieu de travail'), ('service', 'Local de service'), ('autre', 'Autre')], default='boutique', max_length=30)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('maintenance', 'En maintenance'), ('ferme', 'Fermé')], default='libre', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='immo.centrecommercial')),
            ],
            options={
                'ordering': ['centre__nom', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='OccupantCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=180)),
                ('nationalite', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('nom_entreprise', models.CharField(blank=True, max_length=180)),
                ('activite_commerciale', models.CharField(blank=True, max_length=180)),
                ('registre_commerce', models.CharField(blank=True, max_length=100)),
                ('type_piece', models.CharField(choices=[('carte_identite', 'Carte d’identité'), ('passeport', 'Passeport'), ('permis', 'Permis de conduire'), ('carte_consulaire', 'Carte consulaire'), ('autre', 'Autre')], default='carte_identite', max_length=30)),
                ('numero_piece', models.CharField(blank=True, max_length=100)),
                ('date_expiration_piece', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='centres_commerciaux/occupants/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('piece_identite', models.FileField(upload_to='centres_commerciaux/occupants/pieces/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants_commerciaux', to='immo.agence')),
            ],
        ),
        migrations.CreateModel(
            name='ContratCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(editable=False, max_length=60, unique=True)),
                ('code_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_activite', models.CharField(max_length=180)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=14)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('caution_payee', models.BooleanField(default=False)),
                ('conditions', models.TextField(blank=True)),
                ('signe_par_occupant', models.BooleanField(default=False)),
                ('signe_par_gestionnaire', models.BooleanField(default=False)),
                ('certifie_application', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_signature', models.DateField(default=django.utils.timezone.localdate)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_commerciaux', to='immo.agence')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='immo.localcommercial')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='immo.occupantcommercial')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='centrecommercial',
            constraint=models.UniqueConstraint(fields=('agence', 'code'), name='centre_commercial_code_unique_agence'),
        ),
        migrations.AddConstraint(
            model_name='localcommercial',
            constraint=models.UniqueConstraint(fields=('centre', 'numero'), name='numero_local_unique_dans_centre'),
        ),
    ]
