# Generated by Django 6.0.5 on 2026-07-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0015_centrecommercial_localcommercial_occupantcommercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='email_recu',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recu_envoye_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='signature_employe',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/signatures/employes/'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='signature_locataire',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/signatures/locataires/'),
        ),
    ]
